### ISSUE TITLE
Mandatory sign | Shipping details text fields like First name, Mobile number, Complete address, Building name, Pincode and Landmark doesn't contain mandatory sign(*)

### ISSUE THREAD

**Issue by AdithyaRamakrishna** [beckn/bap-reference-app#24]
**STR**:

1.  Launch the  application
2.  Enter valid location
3.  Enter product in the search bar
4.  Enter search
5.  Add products to the cart
6.  Tap view cart
7.  Add valid shipping details

**Severity**: Minor

**Expected Result**: Mandatory fields should be marked with an asterisk(*)

**Actual Result**: Mandatory fields are not marked with an asterisk(*)

**Defect Proof**: https://drive.google.com/file/d/1mPM4bPgdts9qhku2sqxdlUYZ13yuzKWV/view?usp=drivesdk

**Comment by vrushalijatti** [comment]
Mandatory sign added
