### ISSUE TITLE
Sign in | Whenever user is logged out and try to login with Gmail there is no confirmation for logging to the account and user is not able to see for which account he has logged in

### ISSUE THREAD

**Issue by gowthamnu** [beckn/bap-reference-app#6]
**STR:**
1. Launch the browser and navigate to the test URL 
2. Click on Sign In.
3. Click on Sign In with Google

**Severity:** Critical

**Expected Result:** The user should get some confirmation mail.

**Actual Result:** The user should get some confirmation mail.

**Defect Proof:** [](https://drive.google.com/file/d/1P9PVD_6av6oqzjtWYwSoWWtbeg84i4g5/view?usp=sharing)"https://drive.google.com/file/d/1P9PVD_6av6oqzjtWYwSoWWtbeg84i4g5/view?usp=sharing"

**Comment by vrushalijatti** [comment]
Issue fixed
